# Generated by Django 4.2.6 on 2023-11-15 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=10)),
                ('email_ID', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('pin_code', models.PositiveIntegerField()),
                ('request_Type', models.CharField(choices=[], default=' ', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('connect', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
