# Generated by Django 4.2.6 on 2023-11-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='request_Type',
            field=models.CharField(choices=[('english', 'arduino'), ('history', 'motor'), ('electro', 'battery')], default=' ', max_length=50),
        ),
    ]
