# Generated by Django 4.2.6 on 2023-11-15 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electro_app', '0003_rename_customer_request_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='customer_request',
        ),
    ]
